files:
  ./test_project_rs/.git: 1671756009
  ./test_project_rs/.gitignore: 1671756009
  ./test_project_rs/Cargo.lock: 1684687771
  ./test_project_rs/Cargo.toml: 1684691151
  ./test_project_rs/build.rs: 1685117487
  ./test_project_rs/hello.rs: 1684506347
  ./test_project_rs/res/models/Crate/Crate1.3ds: 1671756303
  ./test_project_rs/res/models/Crate/Crate1.blend: 1671756303
  ./test_project_rs/res/models/Crate/Crate1.mtl: 1671756303
  ./test_project_rs/res/models/Crate/CrateImage1.JPG: 1671756303
  ./test_project_rs/res/models/Crate/CrateImage2.JPG: 1671756303
  ./test_project_rs/res/models/Crate/crate_1.jpg: 1671756303
  ./test_project_rs/res/models/Spruce_obj/Spruce branches.png: 1671756303
  ./test_project_rs/res/models/Spruce_obj/Spruce trunk.jpeg: 1671756303
  ./test_project_rs/res/models/Spruce_obj/Spruce.mtl: 1671756303
  ./test_project_rs/res/models/Spruce_obj/Spruce.obj: 1671756303
  ./test_project_rs/res/models/cube/Crate1.mtl: 1671756120
  ./test_project_rs/res/models/cube/container2.png: 1671756120
  ./test_project_rs/res/models/cube/container2_specular.png: 1671756120
  ./test_project_rs/res/models/cube/crate_1.jpg: 1671756120
  ./test_project_rs/res/models/cube/cube.mtl: 1671756120
  ./test_project_rs/res/models/cube/cube.obj: 1671756120
  ./test_project_rs/res/models/nanosuit/LICENSE.txt: 1671756303
  ./test_project_rs/res/models/nanosuit/arm_dif.png: 1671756303
  ./test_project_rs/res/models/nanosuit/arm_showroom_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/arm_showroom_spec.png: 1671756303
  ./test_project_rs/res/models/nanosuit/body_dif.png: 1671756303
  ./test_project_rs/res/models/nanosuit/body_showroom_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/body_showroom_spec.png: 1671756303
  ./test_project_rs/res/models/nanosuit/glass_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/glass_dif.png: 1671756303
  ./test_project_rs/res/models/nanosuit/hand_dif.png: 1671756303
  ./test_project_rs/res/models/nanosuit/hand_showroom_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/hand_showroom_spec.png: 1671756303
  ./test_project_rs/res/models/nanosuit/helmet_diff.png: 1671756303
  ./test_project_rs/res/models/nanosuit/helmet_showroom_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/helmet_showroom_spec.png: 1671756303
  ./test_project_rs/res/models/nanosuit/leg_dif.png: 1671756303
  ./test_project_rs/res/models/nanosuit/leg_showroom_ddn.png: 1671756303
  ./test_project_rs/res/models/nanosuit/leg_showroom_spec.png: 1671756303
  ./test_project_rs/res/models/nanosuit/nanosuit.blend: 1671756303
  ./test_project_rs/res/models/nanosuit/nanosuit.mtl: 1671756303
  ./test_project_rs/res/models/nanosuit/nanosuit.obj: 1671756303
  ./test_project_rs/res/models/ship1/3guns.mtl: 1671756303
  ./test_project_rs/res/models/ship1/3guns.obj: 1671756303
  ./test_project_rs/res/models/ship1/maingun.mtl: 1671756303
  ./test_project_rs/res/models/ship1/maingun.obj: 1671756303
  ./test_project_rs/res/models/ship1/ship.mtl: 1671756303
  ./test_project_rs/res/models/ship1/ship.obj: 1671756303
  ./test_project_rs/res/models/sphere/smooth_sphere.mtl: 1671756120
  ./test_project_rs/res/models/sphere/smooth_sphere.obj: 1673282407
  ./test_project_rs/res/models/sphere/sphere.obj: 1671756120
  ./test_project_rs/res/test.ptem: 1680024344
  ./test_project_rs/res/test2.ptem: 1685536095
  ./test_project_rs/src/build.rs: 1685117487
  ./test_project_rs/src/lib.rs: 1684689540
  ./test_project_rs/src/utils.rs: 1685812589
  ./test_project_rs/target/release/.cargo-lock: 1685125046
  ./test_project_rs/target/release/libtest_project_rs.d: 1685420448
  ./test_project_rs/target/release/libtest_project_rs.rlib: 1687968317
  ./test_project_rs/target/release/libtest_project_rs.so: 1687968324
  ./test_project_rs/target/release/test_project_rs.d: 1685912873
  ./test_project_rs/test.ptem: 1680018210
  ./test_project_rs/test2.ptem: 1682368673
assets:
  lib:
    assets:
      ./test_project_rs/target/release/libtest_project_rs.so: 36
    id_gen: 37
  model:
    assets:
      ./test_project_rs/res/models/Spruce_obj/Spruce.obj: 8
      ./test_project_rs/res/models/cube/cube.obj: 3
      ./test_project_rs/res/models/nanosuit/nanosuit.obj: 4
      ./test_project_rs/res/models/ship1/3guns.obj: 5
      ./test_project_rs/res/models/ship1/maingun.obj: 6
      ./test_project_rs/res/models/ship1/ship.obj: 7
      ./test_project_rs/res/models/sphere/smooth_sphere.obj: 1
      ./test_project_rs/res/models/sphere/sphere.obj: 2
      src/cube/cube.obj: 0
    id_gen: 9
  particle_template:
    assets:
      ./test_project_rs/res/test.ptem: 1
      ./test_project_rs/res/test2.ptem: 2
      default.ptem: 0
    id_gen: 3
  rs:
    assets:
      ./test_project_rs/src/lib.rs: 1
      ./test_project_rs/src/utils.rs: 0
    id_gen: 2
  texture:
    assets:
      ./test_project_rs/res/models/Spruce_obj/Spruce branches.png: 20
      ./test_project_rs/res/models/Spruce_obj/Spruce trunk.jpeg: 21
      ./test_project_rs/res/models/cube/container2.png: 1
      ./test_project_rs/res/models/cube/container2_specular.png: 2
      ./test_project_rs/res/models/nanosuit/arm_dif.png: 3
      ./test_project_rs/res/models/nanosuit/arm_showroom_ddn.png: 4
      ./test_project_rs/res/models/nanosuit/arm_showroom_spec.png: 5
      ./test_project_rs/res/models/nanosuit/body_dif.png: 6
      ./test_project_rs/res/models/nanosuit/body_showroom_ddn.png: 7
      ./test_project_rs/res/models/nanosuit/body_showroom_spec.png: 8
      ./test_project_rs/res/models/nanosuit/glass_ddn.png: 9
      ./test_project_rs/res/models/nanosuit/glass_dif.png: 10
      ./test_project_rs/res/models/nanosuit/hand_dif.png: 11
      ./test_project_rs/res/models/nanosuit/hand_showroom_ddn.png: 12
      ./test_project_rs/res/models/nanosuit/hand_showroom_spec.png: 13
      ./test_project_rs/res/models/nanosuit/helmet_diff.png: 14
      ./test_project_rs/res/models/nanosuit/helmet_showroom_ddn.png: 15
      ./test_project_rs/res/models/nanosuit/helmet_showroom_spec.png: 16
      ./test_project_rs/res/models/nanosuit/leg_dif.png: 17
      ./test_project_rs/res/models/nanosuit/leg_showroom_ddn.png: 18
      ./test_project_rs/res/models/nanosuit/leg_showroom_spec.png: 19
      grass.png: 22
      src/cube/container2.png: 0
    id_gen: 23
working_file: test.yaml
